POST https://func-fiap-store-durable-functions.azurewebsites.net/api/ProcessOrderHttpStart HTTP/1.1
content-type: application/json

{
  "idPedido": 1,
  "idCliente": 1,
  "dataPedido": "2024-01-10T12:00:00",
  "valorTotal": 10.0,
  "pago": false,
  "aprovado": false,
  "items": [
    {
        "IdItem": 1,
        "Preco": 10,
        "Quantidade": 1
    }
  ]
}

###

GET  https://func-fiap-store-durable-functions.azurewebsites.net/api/WarmUp HTTP/1.1
